"""
Schema definitions for the Info Aggregation Module.

These Pydantic models define the data structures used throughout the application.
"""

from datetime import datetime
from typing import List, Optional, Literal
from pydantic import BaseModel, Field, HttpUrl


class QueryRequest(BaseModel):
    """Request model for keyword query aggregation."""
    
    keywords: List[str] = Field(..., min_length=1, description="List of keywords to search")
    providers: List[Literal["bocha", "tavily"]] = Field(
        default=["bocha", "tavily"],
        description="Providers to query (bocha, tavily, or both)"
    )
    generate_variants: bool = Field(
        default=False,
        description="Whether to generate keyword variants using LLM"
    )
    max_results_per_provider: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Maximum results to return per provider (1-100, will be capped at provider limits)"
    )
    client_request_id: Optional[str] = Field(
        None,
        description="Optional client-provided request ID for tracing"
    )


class QueryResult(BaseModel):
    """Canonical result from a provider search."""
    
    keyword: str = Field(..., description="The search keyword")
    provider: Literal["bocha", "tavily"] = Field(..., description="Provider name")
    title: str = Field(..., description="Result title")
    url: HttpUrl = Field(..., description="Result URL")
    snippet: str = Field("", description="Short text excerpt")
    summary: Optional[str] = Field(None, description="Optional generated summary")
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when result was retrieved"
    )
    request_id: str = Field(..., description="Provider or system request ID for tracing")


class CacheRecord(BaseModel):
    """Cache entry for storing query results."""
    
    key: str = Field(..., description="Cache key (provider|keyword hash)")
    value: List[QueryResult] = Field(..., description="Cached query results")
    ttl: int = Field(86400, description="Time-to-live in seconds (default 24h)")
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When this cache entry was created"
    )
    
    def is_expired(self) -> bool:
        """Check if this cache entry has expired."""
        age_seconds = (datetime.utcnow() - self.created_at).total_seconds()
        return age_seconds > self.ttl


class KeywordVariant(BaseModel):
    """A variant of a keyword generated by LLM."""
    
    original: str = Field(..., description="Original keyword")
    variant: str = Field(..., description="Generated variant")
    variant_type: Optional[str] = Field(
        None,
        description="Type of variant (humanized, professional, long-tail, etc.)"
    )


class AggregationResponse(BaseModel):
    """Response model containing aggregated results."""
    
    results: List[QueryResult] = Field(..., description="All aggregated results")
    total_count: int = Field(..., description="Total number of results")
    by_provider: dict = Field(
        default_factory=dict,
        description="Results grouped by provider name"
    )
    request_id: Optional[str] = Field(None, description="Request ID for tracing")
